import MenuContextProvider, { MenuContext } from "@/context/MenuContext";
import MainLayout from "./components/MainLayout";
import "./globals.css";
import ModaleContextProvider from "@/context/ModaleContext";

require('dotenv').config();
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ModaleContextProvider>
          <MenuContextProvider>
            <MainLayout>{children}</MainLayout>
          </MenuContextProvider>
        </ModaleContextProvider>
      </body>
    </html>
  );
}
